Tienda/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('login/', views.iniciar_sesion, name='iniciar_sesion'),
    path('productos/', include('app.productos.urls')),
    path('usuarios/', include('app.usuarios.urls')),
] 

    #path('categorias/', include('apps.categorias.urls')),
    #path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    #path('registrarme/',views.registrarme, name= 'registrarme'),
    #path('login/', views.login, name='login'),

app/productos/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name= "productos"
urlpatterns = [
    path('addprod.html', views.crear_producto, name='crear_productos'),
    path('productos.html', views.listar_productos, name='listar_productos'),
    path('editar/<int:id>/', views.editar_producto, name='editar_producto'),
    path('eliminar/<int:producto_id>/', views.eliminar_producto, name='eliminar_producto'),
    path('lista_favoritos/', views.lista_favoritos, name='lista_favoritos'),
     path('producto/<int:producto_id>/agregar_favorito/', views.agregar_favorito, name='agregar_carrito'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    #path('editar/<int:id>/', views.editar_producto, name='editar_producto'),
    #path('eliminar/<int:producto_id>/', views.eliminar_producto, name='eliminar_producto'),
    #path('desactivar/<int:producto_id>/', views.desactivar_producto, name='desactivar_producto'),
    #path('detalle/<int:producto_id>/', views.detalle_producto, name='detalle_producto'),
    #path('lista_favoritos/', views.lista_favoritos, name='lista_favoritos'),
    #path('producto/<int:producto_id>/agregar_favorito/', views.agregar_favorito, name='agregar_favorito'),
    #path('producto/<int:producto_id>/eliminar_favorito/', views.eliminar_favorito, name='eliminar_favorito'),
    #path('marcar_favorito/<int:producto_id>/', views.marcar_favorito, name='marcar_favorito'),

app/productos/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from django.contrib.auth import get_user_model

class Categoria(models.Model):
    nombre = models.CharField(max_length=100)
    
    def __str__(self):
        return self.nombre
#User = get_user_model()
class Producto(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    imagen = models.ImageField(upload_to='productos/', null=True, blank=True)
    categoria = models.ForeignKey(Categoria, on_delete=models.SET_NULL, null=True, blank=True)  # Asegúrate de que esta línea permita nulos

    def __str__(self):
        return self.nombre

class Favorito(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('user', 'producto')

app/productos/forms.py
from django import forms
from .models import Producto

class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = ['nombre', 'descripcion', 'precio', 'imagen', 'categoria']

app/productos/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Producto, Favorito
from .forms import ProductoForm
from django.contrib.auth.decorators import user_passes_test
from django.contrib import messages
from django.http import HttpResponseForbidden
from django.contrib.auth.decorators import login_required

# def es_admin(user):
#     return user.is_authenticated and user.is_staff
# def detalle_producto(request, producto_id):
#     producto = get_object_or_404(Producto, id=producto_id)
#     return render(request, 'productos/detalles_producto.html', {'producto': producto})

#def listar_productos(request):
#    productos = Producto.objects.all()
#    buscador = request.GET.get('buscador', '')
#    if buscador:
#        productos = productos.filter(nombre__icontains=buscador)
 #   return render(request, 'productos/productos.html', {'productos': productos})
#def listar_productos(request):
#    productos = Producto.objects.all()
#    print(productos)  # Agrega esto para depurar
#    return render(request, 'productos/productos.html', {'productos': productos})
# @user_passes_test(es_admin)
def listar_productos(request):
    # Obtener el valor del buscador desde los parámetros GET
    query = request.GET.get('buscador')

    if query:
        # Filtrar los productos que contienen el texto de búsqueda en su nombre (ignorando mayúsculas y minúsculas)
        productos = Producto.objects.filter(nombre__icontains=query)
    else:
        # Si no hay texto de búsqueda, devolver todos los productos
        productos = Producto.objects.all()

    return render(request, 'productos/productos.html', {'productos': productos})


def crear_producto(request):
    if request.method == 'POST':
        form = ProductoForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('productos:listar_productos')
        else:
            return render(request, 'productos/addprod.html', {'form': form, 'error': 'Error al crear el producto. Por favor, revisa el formulario.'})
    else:
        form = ProductoForm()
    return render(request, 'productos/addprod.html', {'form': form})


# @user_passes_test(es_admin)
def editar_producto(request, id):
    producto = get_object_or_404(Producto, id=id)
    if request.method == 'POST':
        form = ProductoForm(request.POST, request.FILES, instance=producto)
        if form.is_valid():
            form.save()
            return redirect('productos:listar_productos')
    else:
        form = ProductoForm(instance=producto)
    return render(request, 'productos/editProd.html', {'form': form, 'producto': producto})

# @user_passes_test(es_admin)
def eliminar_producto(request, producto_id):
     producto = get_object_or_404(Producto, pk=producto_id)
     if request.method == 'POST':
         # Eliminar el producto
         producto.delete()
         messages.success(request, 'Producto eliminado exitosamente.')
         return redirect('productos:listar_productos')
     else:
         # Mostrar confirmación de eliminación de producto
         return render(request, 'productos/EliminarProd.html', {'producto': producto})
     
def lista_favoritos(request):
    favoritos = Favorito.objects.filter(user=request.user).select_related('producto')
    return render(request, 'productos/listaCarrito.html', {'favoritos': favoritos})


# @user_passes_test(es_admin)
# def desactivar_producto(request, producto_id):
#     producto = get_object_or_404(Producto, pk=producto_id)
#     if request.method == 'POST':
#         producto.activo = False
#         producto.save()
#         messages.success(request, 'Producto desactivado exitosamente.')
#         return redirect('pagina_principal')
#     return render(request, 'productos/desactivar_producto.html', {'producto': producto})

@login_required
def agregar_favorito(request, producto_id):
    producto = get_object_or_404(Producto, id=producto_id)

    # Verifica si el producto ya está en los favoritos del usuario
    if not Favorito.objects.filter(user=request.user, producto=producto).exists():
        Favorito.objects.create(user=request.user, producto=producto)
    
    return redirect('lista_favoritos')   # Redirige a la vista de favoritos

# @login_required
# def eliminar_favorito(request, producto_id):
#     producto = get_object_or_404(Producto, id=producto_id)
#     favorito = Favorito.objects.filter(user=request.user, producto=producto)
#     if favorito.exists():
#         favorito.delete()
#     return redirect('productos:detalle_producto', producto_id=producto.id)

# @login_required
# def lista_favoritos(request):
#     favoritos = Favorito.objects.filter(user=request.user).select_related('producto')
#     return render(request, 'productos/listar_favoritos.html', {'favoritos': favoritos})


# @login_required
# def marcar_favorito(request, producto_id):
#     # Verificar si el usuario es administrador
#     if request.user.is_staff:
#         return HttpResponseForbidden("Forbidden: Solo usuarios registrados pueden marcar como favorito.")

#     producto = get_object_or_404(Producto, id=producto_id)
#     favorito, created = Favorito.objects.get_or_create(user=request.user, producto=producto)
#     if created:
#         messages.success(request, f'El producto {producto.nombre} ha sido añadido a tus favoritos.')
#     else:
#         messages.info(request, f'El producto {producto.nombre} ya está en tus favoritos.')
#     return redirect('productos:lista_favoritos')

templates/productos/EliminarProd.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../../static/styles.css">
    <link rel="stylesheet" href="../../static/Boostrap/bootstrap-5.3.3-dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="../../static/Boostrap/bootstrap-5.3.3-dist/css/bootstrap.css">
    <link rel="stylesheet" href="../../static/Boostrap/bootstrap-5.3.3-dist/css/bootstrap.css.map">
    <link rel="stylesheet" href="../../static/art.css">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="shortcut icon" href="../../img/logo.png" type="image/x-icon">
    <title>BinaryCell</title>
</head>
<body id="cont" class="container-fluid">
  <div class="container-xl" id="divcont2">
    <!-- Mostrar mensajes de error si los hay -->
    {% if form.errors %}
        <div class="alert alert-danger">
            <strong>Se encontraron errores en el formulario:</strong>
            <ul>
                {% for field in form %}
                    {% if field.errors %}
                        <li>{{ field.label }}: {{ field.errors|striptags }}</li>
                    {% endif %}
                {% endfor %}
                {% if form.non_field_errors %}
                    <li>{{ form.non_field_errors }}</li>
                {% endif %}
            </ul>
        </div>
    {% endif %}
    
    <form action="{% url 'productos:eliminar_producto' producto_id=producto.id %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div id="cargaPadmin">
            <div class="input-group" id="nameProd">
                <span class="input-group-text border-warning" id="parttxt">Nombre del Producto</span>
                <input type="text" aria-label="Nombre del Producto" class="form-control border-warning focus-ring focus-ring-warning py-1 px-2 text-decoration-none border rounded-2" name="nombre" value="{{ producto.nombre }}">
            </div>
            <div class="mb-3">
                <label for="productDescription" class="form-label" id="parttxtex">Descripción</label>
                <textarea class="form-control border-warning focus-ring focus-ring-warning py-1 px-2 text-decoration-none border rounded-2 bg-body" name="descripcion" rows="3" >{{ producto.descripcion }}</textarea>
            </div>
            <div id="precioimg">
                <div class="input-group mb-3" id="divprecio">
                    <span class="input-group-text border-warning" id="parttxt">Precio $</span>
                    <input type="text" class="form-control border-warning focus-ring focus-ring-warning py-1 px-2 text-decoration-none border rounded-2" name="precio" aria-label="Amount (to the nearest dollar)" value="{{ producto.precio }}">
                </div>
                <div class="mb-3" id="selectmedia">
                    <label for="productImage" class="form-label" id="parttxtex">Imagen actual del producto</label>
                    <div class="mb-3">
                        {% if producto.imagen %}
                            <img src="{{ producto.imagen.url }}" alt="Imagen actual del producto" class="img-thumbnail" style="max-width: 200px;">
                        {% else %}
                            <p>No hay imagen disponible</p>
                        {% endif %}
                    </div>
                    <label for="productImage" class="form-label" id="parttxtex">Selecciona la imagen del producto</label>
                    <input class="form-control form-control-sm border-warning focus-ring focus-ring-warning py-1 px-2 text-decoration-none border rounded-2 " name="imagen" type="file">
                </div>
            </div>
            <div class="d-grid gap-2 d-md-flex justify-content-md-end" id="btncargaProd">
                <button class="btn btn-warning me-md-2" type="submit">Eliminar</button>
                <button class="btn btn-danger" type="button" id="cancelButton">Cancelar</button>
                <script>
                    document.getElementById('cancelButton').addEventListener('click', function() {
                        window.location.href = "{% url 'productos:listar_productos' %}";
                    });
                </script>
            </div>
        </div>
    </form>
    <footer></footer>
</div>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

templates/productos/addprod.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../../static/styles.css">
    <link rel="stylesheet" href="../../static/Boostrap/bootstrap-5.3.3-dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="../../static/Boostrap/bootstrap-5.3.3-dist/css/bootstrap.css">
    <link rel="stylesheet" href="../../static/Boostrap/bootstrap-5.3.3-dist/css/bootstrap.css.map">
    <link rel="stylesheet" href="../../static/art.css">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="shortcut icon" href="../../img/logo.png" type="image/x-icon">
    <title>BinaryCell</title>
</head>
<body id="cont" class="container-fluid">
  <div class="container-xl" id="divcont2">
    <form action="{% url 'productos:crear_productos' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div id="cargaPadmin">
            <div class="input-group" id="nameProd">
                <span class="input-group-text border-warning" id="parttxt">Nombre del Producto</span>
                <input type="text" aria-label="Nombre del Producto" class="form-control border-warning focus-ring focus-ring-warning py-1 px-2 text-decoration-none border rounded-2" name="nombre">
            </div>
            <div class="mb-3">
                <label for="productDescription" class="form-label" id="parttxtex">Descripción</label>
                <textarea class="form-control border-warning focus-ring focus-ring-warning py-1 px-2 text-decoration-none border rounded-2 bg-body" name="descripcion" rows="3"></textarea>
            </div>
            <div id="precioimg">
                <div class="input-group mb-3" id="divprecio">
                    <span class="input-group-text border-warning" id="parttxt">Precio $</span>
                    <input type="text" class="form-control border-warning focus-ring focus-ring-warning py-1 px-2 text-decoration-none border rounded-2" name="precio" aria-label="Amount (to the nearest dollar)">
                </div>
                <div class="mb-3" id="selectmedia">
                    <label for="productImage" class="form-label" id="parttxtex">Selecciona la imagen del producto</label>
                    <input class="form-control form-control-sm border-warning focus-ring focus-ring-warning py-1 px-2 text-decoration-none border rounded-2 " name="imagen" type="file">
                </div>
            </div>
            <div class="d-grid gap-2 d-md-flex justify-content-md-end" id="btncargaProd">
                <button class="btn btn-warning me-md-2" type="submit">Cargar</button>
                <button class="btn btn-danger" type="button" id="cancelButton">Cancelar</button>
                <script>
                    document.getElementById('cancelButton').addEventListener('click', function() {
                        window.location.href = "{% url 'productos:listar_productos' %}";
                    });
                </script>
            </div>
        </div>
    </form>
    <footer></footer>
</div>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

templates/productos/editProd.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../../static/styles.css">
    <link rel="stylesheet" href="../../static/Boostrap/bootstrap-5.3.3-dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="../../static/Boostrap/bootstrap-5.3.3-dist/css/bootstrap.css">
    <link rel="stylesheet" href="../../static/Boostrap/bootstrap-5.3.3-dist/css/bootstrap.css.map">
    <link rel="stylesheet" href="../../static/art.css">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="shortcut icon" href="../../img/logo.png" type="image/x-icon">
    <title>BinaryCell</title>
</head>
<body id="cont" class="container-fluid">
  <div class="container-xl" id="divcont2">
    <!-- Mostrar mensajes de error si los hay -->
    {% if form.errors %}
        <div class="alert alert-danger">
            <strong>Se encontraron errores en el formulario:</strong>
            <ul>
                {% for field in form %}
                    {% if field.errors %}
                        <li>{{ field.label }}: {{ field.errors|striptags }}</li>
                    {% endif %}
                {% endfor %}
                {% if form.non_field_errors %}
                    <li>{{ form.non_field_errors }}</li>
                {% endif %}
            </ul>
        </div>
    {% endif %}
    
    <form action="{% url 'productos:editar_producto' id=producto.id %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div id="cargaPadmin">
            <div class="input-group" id="nameProd">
                <span class="input-group-text border-warning" id="parttxt">Nombre del Producto</span>
                <input type="text" aria-label="Nombre del Producto" class="form-control border-warning focus-ring focus-ring-warning py-1 px-2 text-decoration-none border rounded-2" name="nombre" value="{{ producto.nombre }}">
            </div>
            <div class="mb-3">
                <label for="productDescription" class="form-label" id="parttxtex">Descripción</label>
                <textarea class="form-control border-warning focus-ring focus-ring-warning py-1 px-2 text-decoration-none border rounded-2 bg-body" name="descripcion" rows="3" >{{ producto.descripcion }}</textarea>
            </div>
            <div id="precioimg">
                <div class="input-group mb-3" id="divprecio">
                    <span class="input-group-text border-warning" id="parttxt">Precio $</span>
                    <input type="text" class="form-control border-warning focus-ring focus-ring-warning py-1 px-2 text-decoration-none border rounded-2" name="precio" aria-label="Amount (to the nearest dollar)" value="{{ producto.precio }}">
                </div>
                <div class="mb-3" id="selectmedia">
                    <label for="productImage" class="form-label" id="parttxtex">Imagen actual del producto</label>
                    <div class="mb-3">
                        {% if producto.imagen %}
                            <img src="{{ producto.imagen.url }}" alt="Imagen actual del producto" class="img-thumbnail" style="max-width: 200px;">
                        {% else %}
                            <p>No hay imagen disponible</p>
                        {% endif %}
                    </div>
                    <label for="productImage" class="form-label" id="parttxtex">Selecciona la imagen del producto</label>
                    <input class="form-control form-control-sm border-warning focus-ring focus-ring-warning py-1 px-2 text-decoration-none border rounded-2 " name="imagen" type="file">
                </div>
            </div>
            <div class="d-grid gap-2 d-md-flex justify-content-md-end" id="btncargaProd">
                <button class="btn btn-warning me-md-2" type="submit">Guardar Cambios</button>
                <button class="btn btn-danger" type="button" id="cancelButton">Cancelar</button>
                <script>
                    document.getElementById('cancelButton').addEventListener('click', function() {
                        window.location.href = "{% url 'productos:listar_productos' %}";
                    });
                </script>
            </div>
        </div>
    </form>
    <footer></footer>
</div>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

templates/productos/productos.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../../static/styles.css">
    <link rel="stylesheet" href="../../static/Boostrap/bootstrap-5.3.3-dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="../../static/Boostrap/bootstrap-5.3.3-dist/css/bootstrap.css">
    <link rel="stylesheet" href="../../static/Boostrap/bootstrap-5.3.3-dist/css/bootstrap.css.map">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="shortcut icon" href="../../img/logo.png" type="image/x-icon">
    <link rel="stylesheet" href="../../static/art.css">
    <title>BinaryCell</title>
</head>
<body id="cont" class="container-fluid">
    <div class="container-xl" id="divcont2">
        <div id="listPadmin" >
            <div class="col-md-4" id="divbus">
                <div class="col">
                    <form method="GET" action="{% url 'productos:listar_productos' %}">
                        <div class="input-group">
                            <input type="text" class="form-control focus-ring focus-ring-warning py-1 px-2 text-decoration-none border rounded-2" name="buscador" placeholder="Buscar">
                            <button type="submit" class="btn btn-outline-warning"><img src="../../img/lupa.png" id="buscador" width="30px" height="30px" alt="Buscar"></button>
                        </div>
                    </form>
                </div>
            </div>
            <div  id="add">
                <div class="btn-group" id="btn2" role="group" aria-label="Basic outlined example">
                    <button id="btnm2" type="button" class="btn btn-outline-success">
                        <a id="linkbtn" href="{% url 'productos:crear_productos' %}"><img src="../../img/addElement.png" width="30px" height="30px" alt="Add Producto"></a>
                    </button>
                    <button id="btnm2" type="button" class="btn btn-outline-warning">
                        <a id="linkbtn" href="{% url 'home' %}"><img src="../../img/home.png" width="30px" height="30px" alt="Home"></a>
                    </button>
                </div>
            </div>
            <div id="contProd" class="col-12">
                <div class="row">
                    {% for producto in productos %}
                    <div class="col-md-4 mb-3">
                        <!-- Aplica la clase product-card a la tarjeta -->
                        <div class="card product-card bg-dark border-warning" style="max-width: 280px;">
                            <!-- Verifica si el producto tiene una imagen -->
                            {% if producto.imagen %}
                            <!-- Ajusta el tamaño de la imagen usando las clases de Bootstrap -->
                            <img src="{{ producto.imagen.url }}" class="img-fluid rounded-start"  alt="{{ producto.nombre }}">
                            {% endif %}
                            <!-- Contenido de la tarjeta -->
                            <div class="card-body">
                                <h5 class="card-title text-light">{{ producto.nombre }}</h5>
                                <p class="card-text text-light">{{ producto.descripcion }}</p>
                                <p class="card-text text-warning" id="precio"><strong>${{ producto.precio }}</strong></p>
                                <div class="d-grid gap-2" id="btnedit">
                                    <button class="btn btn-warning" type="button">
                                        <a href="{%url 'productos:editar_producto' producto.id%}"><img src="../../img/editprod.png" width="15px" height="15px" alt="Editar"></a>
                                    </button>
                                    <button class="btn btn-warning" type="button">
                                        <a href="{%url 'productos:eliminar_producto' producto.id%}"><img src="../../img/dellElement.png" width="15px" height="15px" alt="Editar"></a>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% empty %}
                    <p>No hay productos disponibles.</p>
                    {% endfor %}
                </div>
            </div>
            
        </div>
        <footer></footer>
    </div>
</body>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</html>