Tienda/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('login/', views.iniciar_sesion, name='iniciar_sesion'),
    path('productos/', include('app.productos.urls')),
    path('usuarios/', include('app.usuarios.urls')),
] 

    #path('categorias/', include('apps.categorias.urls')),
    #path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    #path('registrarme/',views.registrarme, name= 'registrarme'),
    #path('login/', views.login, name='login'),

app/usuarios/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
app_name= "usuarios"
urlpatterns = [

    path('registrarse/', views.registrarse, name='registrarse'),
]
    
    #path('registrarse/', views.registrarse, name='registrarse'),
    #path('perfil/', views.ver_perfil, name='ver_perfil'),
    #path('editar/', views.editar_perfil, name='editar_perfil'),
    #path('favoritos/', views.listar_favoritos, name='listar_favoritos'),
    #path('usuarios/', views.lista_usuarios, name='lista_usuarios'),

app/usuarios/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class Usuario(AbstractUser):
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=150, unique=True, default='default_username')

    def __str__(self):
        return self.username



app/usuarios/forms.py
# apps/usuarios/forms.py

from django import forms
from django.contrib.auth.forms import UserCreationForm
from app.usuarios.models import Usuario

class EditarPerfilForm(forms.ModelForm):
    class Meta:
        model = Usuario
        fields = ['username', 'first_name', 'last_name', 'email']

class FormularioRegistroUsuario(UserCreationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    last_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    first_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={'class': 'form-control'})
    )
    password1 = forms.CharField(
        label="Contraseña",
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )
    password2 = forms.CharField(
        label="Repita contraseña",
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )

    class Meta:
        model = Usuario
        fields = ["username", "first_name", "last_name", "email"]

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if Usuario.objects.filter(email=email).exists():
            raise forms.ValidationError("Este correo electrónico ya está en uso.")
        return email

app/usuarios/views.py
from django.shortcuts import render, redirect
from app.productos.models import Producto
from django.contrib.auth.decorators import login_required, user_passes_test
from django.shortcuts import redirect
from django.contrib.auth.models import User
from django.contrib import messages
from .forms import EditarPerfilForm, FormularioRegistroUsuario
from django.contrib.admin.views.decorators import user_passes_test
from django.contrib.auth import authenticate, login
from django.contrib.auth import get_user_model 
from .models import Usuario

User = get_user_model()




# usuarios no autenticados
"""def listar_productos(request):
    productos = Producto.objects.all()
    return render(request, 'productos/listar_productos.html', {'productos': productos})

def ver_detalle_producto(request, producto_id):
    producto = Producto.objects.get(pk=producto_id)
    return render(request, 'productos/detalle_producto.html', {'producto': producto})"""
def registrarse(request):
    if request.method == 'POST':
        form = FormularioRegistroUsuario(request.POST)
        if form.is_valid():
            form.save()  # Guardar el nuevo usuario
            messages.success(request, 'Cuenta creada con éxito. Ahora puedes iniciar sesión.')
            return redirect('iniciar_sesion')  # Redirige a la página de inicio de sesión
    else:
        form = FormularioRegistroUsuario()
    return render(request, 'usuarios/registrarse.html', {'form': form})

#def registrarse(request):
 #   if request.method == 'POST':
 #       form = FormularioRegistroUsuario(request.POST)
 #       if form.is_valid():
 #           form.save()
#            return redirect('login')  # Redirige a la página de inicio o a otra página después del registro
 #   else:
#        form = FormularioRegistroUsuario()
#    return render(request, 'usuarios/registrarme.html', {'form': form})


#usuarios autenticados
#@login_required
def iniciar_sesion(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('home')  # Cambia a 'home' o a otra URL relevante
        else:
            messages.error(request, 'Credenciales inválidas. Por favor, inténtalo de nuevo.')
    return render(request, 'usuarios/login.html')


#@login_required
#def ver_perfil(request):
#    # Obtener el usuario autenticado
#    usuario = request.user
#    return render(request, 'usuarios/ver_perfil.html', {'usuario': usuario})

#@login_required
#def editar_perfil(request):
 #   if request.method == 'POST':
 #       form = EditarPerfilForm(request.POST, instance=request.user)
 #       if form.is_valid():
 #           form.save()
 #           messages.success(request, 'Tu perfil ha sido actualizado exitosamente.')
 #           return redirect('usuarios:ver_perfil')
 #   else:
 #       form = EditarPerfilForm(instance=request.user)
 #   return render(request, 'usuarios/editar_perfil.html', {'form': form})

#usuarios administradores
def es_admin(user):
    return user.is_authenticated and user.is_staff



# Decorador para permitir solo a los administradores acceder a esta vista
@user_passes_test(lambda u: u.is_superuser)
def lista_usuarios(request):
    usuarios = Usuario.objects.all()
    return render(request, 'usuarios/listar_usuarios.html', {'usuarios': usuarios})


templates/usuarios/registrarse.html
<!DOCTYPE html>

<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../static/styles.css">
    <link rel="stylesheet" href="../static/Boostrap/bootstrap-5.3.3-dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="../static/Boostrap/bootstrap-5.3.3-dist/css/bootstrap.css">
    <link rel="stylesheet" href="../static/Boostrap/bootstrap-5.3.3-dist/css/bootstrap.css.map">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="shortcut icon" href="../img/logo.png" type="image/x-icon">
    <link rel="stylesheet" href="../static/art.css">
    <title>BinaryCell - Registro</title>
</head>
<body id="cont" class="container-fluid">

    <h2>Formulario de Registro</h2>
    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label for="id_first_name" class="form-label">Nombre</label>
            <input type="text" name="first_name" maxlength="30" class="form-control" required id="id_first_name">
        </div>
        <div class="mb-3">
            <label for="id_last_name" class="form-label">Apellido</label>
            <input type="text" name="last_name" maxlength="30" class="form-control" required id="id_last_name">
        </div>
        <div class="mb-3">
            <label for="id_username" class="form-label">Nombre de Usuario</label>
            <input type="text" name="username" maxlength="150" class="form-control" required id="id_username">
        </div>
        <div class="mb-3">
            <label for="id_email" class="form-label">Correo Electrónico</label>
            <input type="email" name="email" class="form-control" required id="id_email">
        </div>
        <div class="mb-3">
            <label for="id_password1" class="form-label">Contraseña</label>
            <input type="password" name="password1" class="form-control" required id="id_password1">
        </div>
        <div class="mb-3">
            <label for="id_password2" class="form-label">Confirmar Contraseña</label>
            <input type="password" name="password2" class="form-control" required id="id_password2">
        </div>
        
        <button type="submit" class="btn btn-primary">Registrarse</button>
    </form>
    
    {% if form.errors %}
        <div class="errorlist mt-3">
            <p>Por favor, corrige los errores a continuación:</p>
            <ul>
                {% for field in form %}
                    {% for error in field.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
</body>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</html>