Tienda/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('login/', views.iniciar_sesion, name='iniciar_sesion'),
    path('productos/', include('app.productos.urls')),
    path('usuarios/', include('app.usuarios.urls')),
] 

    #path('categorias/', include('apps.categorias.urls')),
    #path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    #path('registrarme/',views.registrarme, name= 'registrarme'),
    #path('login/', views.login, name='login'),

app/productos/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name= "productos"
urlpatterns = [
    path('addprod.html', views.crear_producto, name='crear_productos'),
    path('productos.html', views.listar_productos, name='listar_productos'),
    path('editar/<int:id>/', views.editar_producto, name='editar_producto'),
    path('eliminar/<int:producto_id>/', views.eliminar_producto, name='eliminar_producto'),
    path('lista_favoritos/', views.lista_favoritos, name='lista_favoritos'),
     path('producto/<int:producto_id>/agregar_favorito/', views.agregar_favorito, name='agregar_carrito'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    #path('editar/<int:id>/', views.editar_producto, name='editar_producto'),
    #path('eliminar/<int:producto_id>/', views.eliminar_producto, name='eliminar_producto'),
    #path('desactivar/<int:producto_id>/', views.desactivar_producto, name='desactivar_producto'),
    #path('detalle/<int:producto_id>/', views.detalle_producto, name='detalle_producto'),
    #path('lista_favoritos/', views.lista_favoritos, name='lista_favoritos'),
    #path('producto/<int:producto_id>/agregar_favorito/', views.agregar_favorito, name='agregar_favorito'),
    #path('producto/<int:producto_id>/eliminar_favorito/', views.eliminar_favorito, name='eliminar_favorito'),
    #path('marcar_favorito/<int:producto_id>/', views.marcar_favorito, name='marcar_favorito'),

app/usuarios/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
app_name= "usuarios"
urlpatterns = [

    path('registrarse/', views.registrarse, name='registrarse'),
]
    
    #path('registrarse/', views.registrarse, name='registrarse'),
    #path('perfil/', views.ver_perfil, name='ver_perfil'),
    #path('editar/', views.editar_perfil, name='editar_perfil'),
    #path('favoritos/', views.listar_favoritos, name='listar_favoritos'),
    #path('usuarios/', views.lista_usuarios, name='lista_usuarios'),

templates/base.html
<!DOCTYPE html>

<html lang="es">

<head>

  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="../static/styles.css">
  <link rel="stylesheet" href="../static/Boostrap/bootstrap-5.3.3-dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="../static/Boostrap/bootstrap-5.3.3-dist/css/bootstrap.css">
  <link rel="stylesheet" href="../static/Boostrap/bootstrap-5.3.3-dist/css/bootstrap.css.map">
  <link rel="shortcut icon" href="../img/logo.png" type="image/x-icon">
  <title>BinaryCell</title>

</head>

<body id="cont" class="container-fluid">

    <div class="container-xl" id="divcont">

        <div id="header">
            <div class="container text-center">
                <div class="row">
                  <div class="col-md-4" id="logo">
                    <img src="../img/logo.png" id="img" width="100px" height="100px" alt="">
                  </div>
                  <div class="col order-5">
                    <h1 id="titulo" class="text-warning">BinaryCell</h1>
                  </div>
                </div>
              </div>
              <div class="btn-group" id="btn" role="group" aria-label="Basic outlined example">
                <button id="btnm" type="button" class="btn btn-outline-warning"><a id="linkbtn" href=""><img src="../img/home.png" width="30px" height="30px" alt=""></a></button>   
                <button id="btnm" type="button" class="btn btn-outline-warning"><a id="linkbtn" href="../productos/productos.html">Administrar</a></button>
                <button id="btnm" type="button" class="btn btn-outline-warning"><a id="linkbtn" href="">Contactos</a></button>
            </div>
            <div class="btn-group" id="btn2" role="group" aria-label="Basic outlined example">
                <button id="btnm2" type="button" class="btn btn-outline-warning"><a id="linkbtn" href="{% url 'productos:lista_favoritos' %}"><img src="../img/carrito.png" width="30px" height="30px" alt="" srcset=""></a></button>
                <button id="btnm2" type="button" class="btn btn-outline-warning"><a id="linkbtn" href="{% url 'iniciar_sesion' %}"><img src="../img/user.png" width="30px" height="30px" alt=""></a></button>
            </div>
        </div>

        <div class="card text-center" id="cardservi">
            <div class="card-header text-warning">
              Servicio Técnico
            </div>
            <div class="card-body">
              <h5 class="card-title text-warning">Contáctanos</h5>
              <p class="card-text text-light">Para reparación de tus dispositivos comunícate con nosotros</p>
              <a href="https://wa.me/+5493644320095" class="btn btn-success">Whatsapp</a>
            </div>
            <div class="card-footer text-body-secondary">
              <p class="text-warning">BinaryCell</p>
            </div>
        </div>

        <div class="col-md-4" id="divbus2">
            <div class="col">
                <form method="GET">
                    <div class="input-group">
                        <input type="text" class="form-control" name="buscador" placeholder="Buscar">
                        <button type="submit" class="btn btn-outline-warning"><img src="../img/lupa.png" id="buscador" width="30px" height="30px" alt=""></button>
                    </div>
                </form>
            </div>
        </div>
        <!-- Sección de productos -->
        <div id="contProd" class="row mt-4 " >
          {% for producto in productos %}
          <div class="col-md-4 mb-3 ">
              <!-- Aplica la clase product-card a la tarjeta -->
              <div class="card product-card bg-dark border-warning" style="max-width: 280px;">
                  <!-- Verifica si el producto tiene una imagen -->
                  {% if producto.imagen %}
                  <!-- Ajusta el tamaño de la imagen usando las clases de Bootstrap -->
                  <img src="{{ producto.imagen.url }}" class="img-fluid rounded-start" alt="{{ producto.nombre }}">
                  {% endif %}
                  <!-- Contenido de la tarjeta -->
                  <div class="card-body">
                      <h5 class="card-title text-light">{{ producto.nombre }}</h5>
                      <p class="card-text text-light">{{ producto.descripcion }}</p>
                      <p class="card-text text-warning"><strong>Precio: ${{ producto.precio }}</strong></p>
                      <div class="d-grid gap-2" id="btnedit">
                        <button class="btn btn-warning" type="button">
                          <a href="{%url 'productos:agregar_carrito' producto.id%}"><img src="../img/addCarrito.png" width="15px" height="15px" alt="Editar"></a>
                        </button>
                      </div>
                    </div>
              </div>
          </div>
          {% empty %}
          <p>No hay productos disponibles.</p>
          {% endfor %}
      </div>

        <footer></footer>

    </div>

</body>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../static/styles.css">
    <link rel="stylesheet" href="../static/Boostrap/bootstrap-5.3.3-dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="../static/Boostrap/bootstrap-5.3.3-dist/css/bootstrap.css">
    <link rel="stylesheet" href="../static/Boostrap/bootstrap-5.3.3-dist/css/bootstrap.css.map">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="shortcut icon" href="../img/logo.png" type="image/x-icon">
    <link rel="stylesheet" href="../static/art.css">
    <title>BinaryCell</title>
</head>
<body id="cont" class="container-fluid">

    <h1>Iniciar sesión</h1>
    <div class="card">
        <div class="card-body">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-danger" role="alert">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
            <form method="post">{% csrf_token %}
                <label class="form-label">Nombre de usuario</label>
                <input type="text" id="username" name="username" class="form-control" value="{{nombre_usuario}}">
                <label class="form-label">Contraseña</label>
                <input type="password" id="password" name="password" class="form-control">
                <hr class="my-4">
                Si aun no tienes una cuenta, <a href="{% url 'usuarios:registrarse' %}">haz click</a> para registrarte

                <button class="w-100 btn btn-primary btn-lg mt-3" type="submit">Iniciar sesion</button>
            </form>
        </div>
    </div>

    <!-- Scripts -->
    
</body>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</html>